---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secrets
  namespace: searxng
spec:
  encryptedData:
    SEARXNG_SECRET: AgCY8Nb3U6KWyvMe+tRthh+VB/qvZMFXQREokM1QTQcCO97dcCvRMPCAuCtqAehUIa5df0EkHDJLjw6RUcJELeFAq6y9696HSf4TxwVFlj2/WIV319n4YYWaW73uBOy0INzG+gc1C7OgRGdjx37olQkXCkCCHnthqDMsVIvcbyZ4pHYHZVdWbw9dtF3aFpsjwTDDv1aFqcbFgDwvCROQCqUHxkwD+PBOnYvbFHhAU6meWPuMYBeBic0EkpPZpxcY3qEvxctDuBlz3/WDeDxXg0ebaw363xAF9eQQTb5FzkKYnBSbzUoPmJPOrp+Qx1P6BQrNK1OO5EDIvtmSkIs/3kPr+tH6HLRx521t2bF97ssEy+hBPZ/z0gKoK1r3PenK7ryO+S6TqWp7+jhPrjP4K9Gt3cqcbZ8ngU433YyFiuS5yaGdzYBXPgp1NF+YLoiobxOe+GF6BhTMBvuaC7DWMslHoPEN2FW1q6F+uahN+oJvltecLib7YEe57Wm7jUen2KEaBRIuiBBqidkC7sKX1qKjyofzyQ0F0m8VbyJyi+gvNxJbXyXUg62XBgqdXAAnb2wLMP+aBh3Rjpnb69eYxmnXLlT7HJlIxWtphn/K26+G/e8Mq6Uwk59RWkY0MuJAfm36caE5FfEgHLTW/YDeD2c26V5dSSsttNI62OPGx2voVASMVqNA5uXOtJ/YWMOg+JAnxpM20PiiaExtLyNktz4Bz1Eca0Rgbtj0wMyymNAiJA==
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secrets
      namespace: searxng
    type: Opaque
