---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: vllm-secret
  namespace: vllm
spec:
  encryptedData:
    KEY: AgCzbb6PKxuSmky64Ont6efn9Gq+ucE83cBrsOo3riWS3PknvYwGQFDSTdur6CyYDIHdPm5SUmTlR6YqbxfstzE63CdNBlD10csgDPFi3XLLZMxX3lb/ZQoZtM6NojH0UL6gPuy1OCucP0u9bejMXtvn4zgPfVcBWnztOXXrFXxghP/BWrh2dUdOehjLbmuMDnvqOomkhAKO1eTYcRfs7TH1uFlTApHWekW/+0osjK/WUCw6Jh8AbW/NSOZTU8QNmcYoZkqEXU1uPhV6PamUkNa2zbdeh3zzABuahgiaQYKiSdtQUDqSQBNvlxNsIZ90Cc0ggrH5hikAw673D4oTTMyIxiPjZDr+uoYUAxBzCdk8jluKxe4pFXEm88MvHdbNG/iam8R+aw4wps6ac5a8DM7FLs1d3bfiBWR9v0/X2oXSgeVFlG3lIqDEOURjcUgL2p1k73Nfg3OjH88GBHVaR6QBziXKtYciHFVcfFZOOxYWqHK1iMVDZ4TLs3Am08SDHS0Y1QkfxUSZmx3vBiVXHVXtRtyvmGNcmzr9ZkZLzdl/A/w7TVAeVfiOjaM6VBNClxJ/p+8uPMIWsaL7a7E9I90Yx1uQqbeJBXO0dXqJLixanAr/M4w4u0dF+bx83mQhFyYlvh6UcKYGNCjsZPLlhavdBxLVoK3cHQZM/A8CobIpDudlZLTz/lKa3fWL3NCPffvaXF41H7a/EwkaODKjA5imEavG/dg3Eo7hh/APY+mlRA==
  template:
    metadata:
      creationTimestamp: null
      name: vllm-secret
      namespace: vllm
    type: Opaque
