---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudnative-pg-cluster-openwebui
  namespace: openwebui
spec:
  encryptedData:
    password: AgC4ZguPKvEDbYoOJeEjQ/QDf5LUz+ldoftQDhxAYfrb5RGDh5W6G08YtyR4tBeuxjPxJUaKg4vILaLu4AEIHO3FmGeWYe4PAEgb6F3iY+6AJbkADiAqsLs1Mo0byPDe/VHyDkFDIGdJHeqYINrctA07KaUf0+s9eDCmCWRz4sZ/qTFiW6Ho4iy57iL+G6xxhLESHA7FtrXJ3wBWI0fF7d9cP//2EzaxlgXtwWOrvhNVG6y6XnOVGL1ZFmVJqIzyx8Jx2/y/l4OhkHh5CACzzSNH5lMkrvcLiA/vv3oVgDk/12xq2yEflX7E6E6jYDY0tEcHzPvP759oZgPKztogFT4MTnB2iAtmzqRwdIowwH5vn2027wI4r1RpGGJs7jrxNh0S1QWGzBkK7V0h7LLw+6F6AGi+fya2Jhx5xQB2ENiYPMHOetk2m3Ljv+AmWRYvgXk2eBgxeMSXO2VP6f3qt3sGzDS5MF+ZEzyUwVOQGX3Ux7vz2rcF3GShH+pGzGoiTgEP8Qg7/X8TZI0qjx03zhF7UOfBbbdWSRhpyjSCcXS1aLlqBxh0zieQV1Hq7fAtJoIKXVNPpcb1fDmQGNzEa20lbDdNAqkgbPWRO4F6Ymu20yfUbfVVjEsGBoafoNWLmzqufgjBVkKKqjgF08iK5lfWPzxivNev3hdRX0sIhxkcGI3gA8/aITbVgKwuXJ49ilkThJ2+HM64SGLJ6svBQYanUl1/FqThd24L973OZBGVaw==
    username: AgChxES7h8MwsKsMA4OtpIqC05JQRHcEhKlaTUMvJKv9zpQvhUWmtQbrAMYKyA59msoOyavBVm1W+cSzahZGftA9OAJ6fdejAmE5SB2tR6mi3zK1qaHghbmtelW5PprzmEXeeg9ypmFu3tj/B/v5nsiVVs9q9sNyuppxOdQVyF2c+jW5BA0Y8drbFnFQQBoXT3sB+YtiRFZGuQOYo3uYD9Xa9re1Edk+kzVLmaD4aoOePCTk0H4UvIe/zh6UbFCRl7iILfFSTUbz7+PZcg2yO1leoBUbKJek3P6VeXi/TKKR/Rx8NgCXmvbT8cv66/M3QzaxFYc274fi+hzOFK+xKsfWhJlPxSywYr3twteC6m71oU46R2KQSUg9uUO8d1wK9sy/0XUxOA1mfPHg2QFnU08fzfZ8kDgu08AO4Ap1A6sCSOx+FIsOO4RwEjl8oQw2fPDwjU2KmcSCeKJJmh5fGmGsKYvq1OrfIYpkSpG2+V/3NNuJFUAvI/2ShMLyfU00Zct7ZrNvkZeB1mw0RtiLBdcDiHos8FILAT331RCLuFiFZRq/dSsdBVE+EBO+JYJcVgXoZ9RKtwkZcDZ8bMc/PGcoJdJhnXwxpl1VnfrOdzZl2vHQ4D+/OQtMQuAofAuZlHuWT6dAx8byR8m7OcqgeKxAhhG7oA4xazMg4+Ti8FmS0ZntAUTfzpYoP284eEj1szsEnQtN9jg9VTg=
  template:
    metadata:
      creationTimestamp: null
      name: cloudnative-pg-cluster-openwebui
      namespace: openwebui
    type: Opaque
