---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: litellm-secrets
  namespace: litellm
spec:
  encryptedData:
    CA_VLLM_LOCAL_API_KEY: AgDNc8IdxLxDC0FSzge4jW7uVggAQJ1u41AkitAMsW3zlvvF3EuJ843fcAaJ0KZNgnGDP2KFwOZkTKtmRWoi+8v2HgiHWdR4wtiWbLxU8pjV4ItnaeumaQmjDgEq8ak+UxDmLE9/1C74lFKhr1ASegNPszm5mfNF6OZ3gIEx2v3M6RuVrNTAYUsW4B+6rWEpyrbeFk3h45tsD4a6LBbH5SBacD/fVYYd396kI8OkdkrLOTOSV7YcU9rNkud+aWPjFRvxE1SZiVZUQUq+HmnOnZP4Jb0lG5AFZ40eCCySnsLtPs3F0zkoEcP53EUyb2AwGLf3zqVht/5ZX41/qLL1uOBSqkmFwi1tFoVgFc4zn6hUpu8KD+TwixThfIwlF/NXUfGttGy6pX+3BikB3rrKYzZIBVl9Mxk0F5URohd1IdCru46qGBnoGGdfxP9BT2GQIDTYnbFFm8izfmYvfNwwQpoziAUv8hyztnqIOxW0gsdvYGqoNzSwvzAY1/UfazFDLiaBrkoL4uiOcFtmfHfBmwBnS0SuTgajD36qXVQt4E54cPr2uk7wRhuYZXH3XK4un4EI084KsMBbm/jj2FpyEWTLk81hNOHDMe4k1xiW19rLwwEve2Sa/gT8M/+K8rwoS8Me8O2c+rZKofr1+OdCDUCrmKfV1fvdaUZeBQraui5UZqQVBhuHjazhf3UDxlYGZH/erxMNjucP63BsT7G5PVRMse71UrW2OoGV4oM8EBms2g==
    PROXY_MASTER_KEY: AgB8U+7SSJG4+6CUPiQ+jM/kDRrorCxJX6Ykdrb/S6LiZsqnCF8jbWuENPU4B/H5j2DwZwe1tIky6w9yjRZyfUefkCCJjIw/bvyUlwcJEEO0rMvT/2FLvgaukuRe/LfxP7OOHtL2oAEccYVWCIJpdBv/p2vWw+7M7J3DBKfkTVTeGXNrHIkSoOMKAoogyTDiG9vsA+wEW/nPoZ65SP7Spbgm2ssD1jU9jXR6RweC4TBkOnls4v+2kVWg0xnI6dOsmSqeZU7gB9+vP5fxQH9ykbLlFcjSAWSzZt48s2e7dAI+S/DE8IFoFlYxElq82QlMJygDYofYpDkOssiuV+nrDtJkftg7pT+uMF5sXFKUdc9InvsPCpVeWMrOxsCUv1yn7gAuQM1Uvc789IeY3FV7rncUnUzDQiZrb/Iy7m/yNO29DgM7cbiKoBrDYIN8ojN/eXvt0kKMc0MLMFeNiIcHHe95YooTcaCpoeZ1hNPcBnuWtM+sPiauoWsh+sxDAhEF2bZqrrw3CRR87ieHt/gAicHf9P92JUrr/e1510OtyZPoMrCDfXYfeKOU5VJB7eANuB0gS2lrnEEH/dR1bq9KZrnqkr3ZKJgUcEeu+ggkFDNKoCpwEGl5E9H2NYt+N/oeyRwtruJYAwtjRPkP2aH24nGoNb/IbXDKrsipQbFfhhtK0o8Za7HsKEUbOdN1buucRgReiKUwelYlSd4BlnUO9ppZQosc8eBze7cAslyX8qQ9pbhozg==
  template:
    metadata:
      creationTimestamp: null
      name: litellm-secrets
      namespace: litellm
    type: Opaque
